name: makeittalk
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - torchtext
  - pytorch-cuda=11.8
  - pip:
      - matplotlib
      - tensorboardX
      - ffmpeg-python
      - opencv-python
      - face_alignment
      - scikit-learn
      - pydub
      - pynormalize
      - soundfile
      - librosa==0.8.1
      - pysptk
      - pyworld
      - resemblyzer==0.1.1.dev0
